export default [
	{	
		key:"A",   
	    data:[
	    	{title:'鞍山'},{title:'安阳'},{title:'安庆'},{title:'安康'},{title:'阿克苏'},{title:'安顺'},{title:'阿勒泰'},{title:'阿拉善'},{title:'阿坝'},{title:'阿里'},{title:'阿拉尔澳门'}
	    ]
	    
	},
	{
	    key:"B",
	    data:[
	    	{title:'北京'},{title:'保定'},{title:'滨州'},{title:'包头'},{title:'宝鸡'},{title:'本溪'},{title:'蚌埠'},{title:'北海'},{title:'巴彦淖尔'},{title:'白城'},{title:'白山'},{title:'亳州'},{title:'巴中'},{title:'白银'},{title:'百色'},{title:'毕节'},{title:'巴音郭楞'},{title:'保山'},{title:'博尔塔拉'}
	    ]
	},
	{
	    key:"C",
	    data:[
	    	{title:'成都'},{title:'重庆'},{title:'长沙'},{title:'长春'},{title:'常州'},{title:'沧州'},{title:'赤峰'},{title:'承德'},{title:'常德'},{title:'长治'},{title:'郴州'},{title:'滁州'},{title:'巢湖'},{title:'潮州'},{title:'昌吉'},{title:'池州'},{title:'楚雄'},{title:'崇左'},{title:'昌都'},{title:'朝阳'},{title:'常熟'},{title:'慈溪'}
	    ]
	},
	{
	    key:"D",
	    data:[
	    	{title:'大连'},{title:'东莞'},{title:'德州'},{title:'东营'},{title:'大庆'},{title:'大同'},{title:'丹东'},{title:'儋州'},{title:'德阳'},{title:'达州'},{title:'大理'},{title:'大兴安岭'},{title:'定西'},{title:'德宏'},{title:'迪庆'},{title:'钓鱼岛'}
	    ]
	},
	{
	    key:"E",
	    data:[
	    	{title:'鄂尔多斯'},{title:'恩施'},{title:'鄂州'}
	    ]
	},
	{
	    key:"F",
	    data:[
	    	{title:'福州'},{title:'佛山'},{title:'抚顺'},{title:'阜阳'},{title:'阜新'},{title:'抚州'},{title:'防城港'}
	    ]
	},
	{
	    key:"G",
	    data:[
	    	{title:'广州'},{title:'贵阳'},{title:'桂林'},{title:'赣州'},{title:'广元'},{title:'广安'},{title:'贵港'},{title:'固原'},{title:'甘南'},{title:'甘孜'},{title:'果洛'}
	    ]
	},
	{
	    key:"H",
	    data:[
	    	{title:'杭州'},{title:'惠州'},{title:'哈尔滨'},{title:'合肥'},{title:'呼和浩特'},{title:'海口'},{title:'邯郸'},{title:'菏泽'},{title:'衡水'},{title:'淮安'},{title:'衡阳'},{title:'葫芦岛'},{title:'淮南'},{title:'汉中'},{title:'怀化'},{title:'淮北'},{title:'黄冈'},{title:'湖州'},{title:'黄石'},{title:'呼伦贝尔'},{title:'河源'},{title:'鹤壁'},{title:'鹤岗'},{title:'黄山'},{title:'红河'},{title:'河池'},{title:'哈密'},{title:'黑河'},{title:'贺州'},{title:'海西'},{title:'和田'},{title:'海北'},{title:'海东'},{title:'黄南'}
	    ]
	},
	{
	    key:"J",
	    data:[
	    	{title:'济南'},{title:'济宁'},{title:'吉林'},{title:'锦州'},{title:'金华'},{title:'嘉兴'},{title:'江门'},{title:'荆州'},{title:'焦作'},{title:'晋中'},{title:'佳木斯'},{title:'九江'},{title:'晋城'},{title:'荆门'},{title:'鸡西'},{title:'吉安'},{title:'揭阳'},{title:'景德镇'},{title:'济源'},{title:'酒泉'},{title:'金昌'},{title:'嘉峪关'},{title:'胶州'},{title:'即墨'}
	    ]
	},
	{
	    key:"K",
	    data:[
	    	{title:'昆明'},{title:'开封'},{title:'喀什'},{title:'克拉玛依'},{title:'库尔勒'},{title:'克孜勒苏'},{title:'昆山'}
	    ]
	},
	{
	    key:"L",
	    data:[
	    	{title:'兰州'},{title:'拉萨'},{title:'廊坊'},{title:'临沂'},{title:'洛阳'},{title:'聊城'},{title:'柳州'},{title:'连云港'},{title:'临汾'},{title:'漯河'},{title:'辽阳'},{title:'乐山'},{title:'泸州'},{title:'六安'},{title:'娄底'},{title:'莱芜'},{title:'龙岩'},{title:'吕梁'},{title:'丽水'},{title:'凉山'},{title:'丽江'},{title:'六盘水'},{title:'辽源'},{title:'来宾'},{title:'临沧'},{title:'陇南'},{title:'临夏'},{title:'林芝'}
	    ]
	},
	{
	    key:"M",
	    data:[
	    	{title:'绵阳'},{title:'牡丹江'},{title:'茂名'},{title:'梅州'},{title:'马鞍山'},{title:'眉山'}
	    ]
	},
	{
	    key:"N",
	    data:[
	    	{title:'南京'},{title:'宁波'},{title:'南宁'},{title:'南昌'},{title:'南通'},{title:'南阳'},{title:'南充'},{title:'内江'},{title:'南平'},{title:'宁德'},{title:'怒江'},{title:'那曲'}
	    ]
	},
	{
	    key:"P",
	    data:[
	    	{title:'平顶山'},{title:'濮阳'},{title:'盘锦'},{title:'莆田'},{title:'攀枝花'},{title:'萍乡'},{title:'平凉'},{title:'普洱'},{title:'郫县'}
	    ]
	},
	{
	    key:"Q",
	    data:[
	    	{title:'青岛'},{title:'琼海'},{title:'秦皇岛'},{title:'泉州'},{title:'齐齐哈尔'},{title:'清远'},{title:'曲靖'},{title:'衢州'},{title:'庆阳'},{title:'七台河'},{title:'钦州'},{title:'潜江'},{title:'黔东南'},{title:'黔南'},{title:'黔西南'}
	    ]
	},
	{
	    key:"R",
	    data:[
	    	{title:'日照'},{title:'日喀则'}
	    ]
	},
	{
	    key:"S",
	    data:[
	    	{title:'上海'},{title:'深圳'},{title:'沈阳'},{title:'石家庄'},{title:'苏州'},{title:'汕头'},{title:'商丘'},{title:'三亚'},{title:'宿迁'},{title:'绍兴'},{title:'十堰'},{title:'四平'},{title:'三门峡'},{title:'邵阳'},{title:'上饶'},{title:'遂宁'},{title:'三明'},{title:'绥化'},{title:'石河子'},{title:'宿州'},{title:'韶关'},{title:'松原'},{title:'随州'},{title:'汕尾'},{title:'双鸭山'},{title:'朔州'},{title:'石嘴山'},{title:'商洛'},{title:'神农架'},{title:'山南'},{title:'双流'}
	    ]
	},
	{
	    key:"T",
	    data:[
	    	{title:'天津'},{title:'太原'},{title:'唐山'},{title:'泰安'},{title:'台州'},{title:'泰州'},{title:'铁岭'},{title:'通辽'},{title:'通化'},{title:'天水'},{title:'铜陵'},{title:'铜川'},{title:'铜仁'},{title:'天门'},{title:'塔城'},{title:'吐鲁番'},{title:'图木舒克'}
	    ]
	},
	{
	    key:"W",
	    data:[
	    	{title:'武汉'},{title:'无锡'},{title:'乌鲁木齐'},{title:'威海'},{title:'潍坊'},{title:'温州'},{title:'芜湖'},{title:'渭南'},{title:'乌海'},{title:'梧州'},{title:'乌兰察布'},{title:'武威'},{title:'文山'},{title:'吴忠'},{title:'五家渠'},{title:'五指山'}
	    ]
	},
	{
	    key:"X",
	    data:[
	    	{title:'西安'},{title:'厦门'},{title:'西宁'},{title:'徐州'},{title:'咸阳'},{title:'邢台'},{title:'襄阳'},{title:'新乡'},{title:'湘潭'},{title:'许昌'},{title:'信阳'},{title:'孝感'},{title:'忻州'},{title:'咸宁'},{title:'新余'},{title:'宣城'},{title:'仙桃'},{title:'锡林郭勒'},{title:'湘西'},{title:'兴安'},{title:'西双版纳香港'}
	    ]
	},
	{
	   	key:"Y",
	    data:[
	    	{title:'银川'},{title:'宜昌'},{title:'烟台'},{title:'扬州'},{title:'盐城'},{title:'营口'},{title:'岳阳'},{title:'运城'},{title:'榆林'},{title:'宜宾'},{title:'阳泉'},{title:'延安'},{title:'益阳'},{title:'永州'},{title:'玉林'},{title:'宜春'},{title:'阳江'},{title:'延边'},{title:'玉溪'},{title:'伊犁'},{title:'云浮'},{title:'伊春'},{title:'雅安'},{title:'鹰潭'},{title:'玉树'},{title:'义乌'}
	    ]
	},
	{
	    key:"Z",
	    data:[
	    	{title:'郑州'},{title:'珠海'},{title:'淄博'},{title:'中山'},{title:'枣庄'},{title:'张家口'},{title:'株洲'},{title:'镇江'},{title:'周口'},{title:'湛江'},{title:'驻马店'},{title:'肇庆'},{title:'自贡'},{title:'遵义'},{title:'漳州'},{title:'舟山'},{title:'张掖'},{title:'资阳'},{title:'张家界'},{title:'昭通'},{title:'中卫'}
	    ]
	}
]