export default [{
	key:1,
	imglink:require('./../../reactimg/fashionimg/banner1.png'),
	imgcontent:'夏季流行',
	shoescon:'高跟鞋',
	shoelin:require('./../../reactimg/fashionimg/shoes1.png'),
},{
	key:2,
	imglink:require('./../../reactimg/fashionimg/banner2.png'),
	imgcontent:'时尚流行',
	shoescon:'松糕鞋',
	shoelin:require('./../../reactimg/fashionimg/shoes2.png'),
},{
	key:3,
	imglink:require('./../../reactimg/fashionimg/banner3.png'),
	shoelin:require('./../../reactimg/fashionimg/shoes3.png'),
	imgcontent:'返璞归真',
	shoescon:'单鞋',
},{
	key:4,
	imglink:require('./../../reactimg/fashionimg/banner4.png'),
	shoelin:require('./../../reactimg/fashionimg/shoes4.png'),
	imgcontent:'轻易毛衫',
	shoescon:'厚底鞋',
}]