export default [{
	headimg:require('./../../reactimg/person1.png'),
	name:"Krystal",
	status:'在线',
	age:"22岁",
	city:'北京   东城',
	content:"一个人走过, 一个人过, 一个人生活",
},{
	headimg:require('./../../reactimg/person2.png'),
	name:'风雨飘雪',
	status:'在线',
	age:"24岁",
	city:'上海   静安',
	content:"陈星是猩猩的化身",},
	{
	headimg:require('./../../reactimg/person3.png'),
	name:"Krystal",
	status:'离线',
	age:"26岁",
	city:'北京   海淀',
	content:"高兴就好",},
	{
	headimg:require('./../../reactimg/person4.png'),
	name:"Krystal",
	status:'在线',
	age:"22岁",
	city:'四川   成都',
	content:"认真的对待，真诚找朋友",},
	{
	headimg:require('./../../reactimg/person5.png'),
	name:"Krystal",
	status:'在线',
	age:"22岁",
	city:'北京   石景山',
	content:"找呀找呀找朋友",
},	{
	headimg:require('./../../reactimg/person6.png'),
	name:"山鸡哥",
	status:'在线',
	age:"22岁",
	city:'北京   石景山',
	content:"找呀找呀找朋友",
},	{
	headimg:require('./../../reactimg/person5.png'),
	name:"Krystal",
	status:'在线',
	age:"22岁",
	city:'北京   石景山',
	content:"找呀找呀找朋友",
},]